kind: Deployment
apiVersion: apps/v1
metadata:
# set your lab user name
  name:  {{ .Release.Name }}
spec:
  replicas:  {{ .Values.ReplicaNumber }}
      volumes:
        - name: index-html
          configMap:
            name: index.html
            defaultMode: 420
  selector:
    matchLabels:
# set your lab user name
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - resources: {}
        volumeMounts:
          - name: index-html
            mountPath: /tmp/html # this will mount the html.index file to it application location
          terminationMessagePath: /dev/termination-log
          name: {{ .Release.Name }}
          ports:
            - containerPort:  {{ .Values.containers.containerPort }}
              protocol: TCP
          imagePullPolicy: IfNotPresent
          image: {{ .Values.containers.image }}:{{ .Values.containers.tag }}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10